### ISSUE TITLE
Cambiar nombres de directorios y mejorar documentación sobre datasets

### ISSUE THREAD

**Issue by ocorcho** [juanbm99/TFG-OpenCityData-JuanBernal#10]
Se deberían usar nombres de directorios más comunes y en inglés:
/data/
/data/original/
/data/preprocessed/
/data/rdf/

Asegura también que haya una descripción clara, en el README de /data/, de lo que significa cada fichero .csv en esos directorios, pues tienes muchos v1, v2, etc. Es bueno describir el pipeline de procesamiento para que se pudiera replicar.

**Comment by juanbm99** [comment]
He reorganizado ya todos los directorios como has mencionado Oscar, cierro el la issue.
