### ISSUE TITLE
Al terminar de transformar los datos de Madrid, hacerlo con Zaragoza también

### ISSUE THREAD

**Issue by ocorcho** [juanbm99/TFG-OpenCityData-JuanBernal#12]
En el README se ha incluido enlace a datos abiertos de Zaragoza que hacen los datos disponibles en un fichero comprimido ZIP.

**Comment by juanbm99** [comment]
He intentado descargar los ZIP pero no deja porque salta una petición HTTP 404 de recurso no disponible

**Comment by juanbm99** [comment]
Sabemos como poder coger estos datos, siguen sin poder descargarse
