### ISSUE TITLE
RDF Generated and Mappings Updated

### ISSUE THREAD

**Issue by juanbm99** [juanbm99/TFG-OpenCityData-JuanBernal#13]
He terminado la generación de datos RDF y lo he subido conjuntamente con los mappings, @ocorcho cuando tengas un ratillo échales un vistazo y me dices si están correctamente generados.
Muchas gracias, un saludo

**Comment by ocorcho** [comment]
En ruido 2020 me has subido un .rar. Esto no se debe subir así a un repositorio, por muy grandes que sean los datos, pues no se puede revisar directamente.

**Comment by ocorcho** [comment]
He generado nuevos issues #14 y #15 en relación con esta petición, y generaré el #16 sobre las observaciones

**Comment by juanbm99** [comment]
Perfecto me pongo a corregir las cosas. Subí un rar debido a que no me dejaba hacer push al repositorio por el tamaño del fichero. Alguna idea para solucionar esto?
