### ISSUE TITLE
Generar correctamente las observaciones

### ISSUE THREAD

**Issue by ocorcho** [juanbm99/TFG-OpenCityData-JuanBernal#16]
Se ha generado el RDF incorrectamente para las observaciones. En primer lugar, no se comprende por qué se genera de nuevo todo el detalle de las estaciones de medida, pues ya está generado en otro fichero RDF. En segundo lugar, una representación de una observación como la siguiente no es correcta:
>`
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#Observacion>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS50> "058.7"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS01> "070.9"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://www.w3.org/ns/sosa/resultTime> "1/1/2021"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAeq> "063.3"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS99> "041.2"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS10> "067.5"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS90> "049.2"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-intervalo-referencia> "T"^^<http://www.w3.org/2001/XMLSchema#string>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80> <http://www.w3.org/ns/sosa/madeBySensor> <http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/paseo-recoletos>.
`

Lo que se debe hacer es lo siguiente:
- Por cada parámetro que se observa, se genera una observación (no se pueden observar múltiples parámetros en la misma instancia de observación)
- El SKOS determina el tipo de parámetro que se está observando, y no es una propiedad para asignar el valor
- Lo mismo ocurre con el intervalo de referencia
- Falta el tiempo de la observación

**Comment by ocorcho** [comment]
Una observación concreta debería ser:
>`
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#Observacion>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> <http://www.w3.org/ns/sosa/madeBySensor> <http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/paseo-recoletos>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> sosa:observedProperty <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#nivelRuido>
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#tipoMedicion> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS50>
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#tipoIntervaloReferencia> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-intervalo-referencia/T> .
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> sosa:resultTime "2020-12-12T10:05:23"^^xsd:dateTime 
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS50> sosa:simpleResult "58.7"^^xsd:float 
`

Y otra observación 

>`
Y otra observación sería
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#Observacion>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> <http://www.w3.org/ns/sosa/madeBySensor> <http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/paseo-recoletos>.
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> sosa:observedProperty <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#nivelRuido>
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#tipoMedicion> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS01>
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> <http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#tipoIntervaloReferencia> <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-intervalo-referencia/T> .
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> sosa:resultTime "2020-12-12T10:05:23"^^xsd:dateTime 
<http://datos.linkeddata.es/madrid/recurso/medio-ambiente/contaminacion-acustica/observacion/3135268ab00038d2043ea8f536cc4b80-LAS01> sosa:simpleResult "70.9"^^xsd:float 
`
Y así por cada uno de los valores.

**Comment by juanbm99** [comment]
He resubido los rdf, creo que esta vez están correctos.

**Comment by ocorcho** [comment]
Ok. Prepara algunos ejemplos que se puedan explicar con facilidad, así como un listado de FAQ basadas en las interacciones que hemos tenido:
- ¿Qué URIs me aconsejas usar para las estaciones de medida?
- ¿Qué contiene cada observación?
- ¿Qué ocurre si no tengo la  hora exacta de la observación?
etc.
Esto puede ir en un README y será útil para añadirlo como documentación al vocabulario

**Comment by ocorcho** [comment]
Errores detectados:
- cuando un label es de tipo date, debe seguir el formato para xsd:date. Actualmente veo cosas como 1/1/2021, que no se parsearán correctamente.
- Los valores de simpleResult se generan de manera rara. Por ejemplo, "063.3"^^xsd:float en lugar de "63.3"^^xsd:float
- El valor de tipoIntervaloReferencia aparece como un string, en lugar de como una URI.

**Comment by juanbm99** [comment]
Cambiado todo lo comentado
