### ISSUE TITLE
RDF Estaciones Medida Zaragoza

### ISSUE THREAD

**Issue by juanbm99** [juanbm99/TFG-OpenCityData-JuanBernal#17]
He generado los datos para las estaciones de medida de Zaragoza. Un par de dudas: 
- El código postal, al igual que en las de Madrid (aunque los busqué manualmente ya que eran 30 estaciones) no se incluye y la agregación de estos manualmente puede ser muy pesada. Lo dejo sin incluir sin problemas?
- En los datos de Zaragoza se incluye la Calle donde se sitúa la estación y el tramo (se referencia en los campos calle_2 y calle_3) en los que se realiza la medida. En los datos de estaciones he identificado cada estación con la calle donde se encuentra pero no he hecho referencia al tramo ya que considero que esto es algo mas propio de la observacion. Es correcto?
- No he incluido fechas de alta ya que no se referencian en el CSV y las únicas fechas que hay disponibles son aquellas que indican en que fecha se ha realizado la observacion.

**Comment by ocorcho** [comment]
De acuerdo con todo. Déjalo documentado, sin problema.

**Comment by juanbm99** [comment]
Al mapear las observaciones me he dado cuenta de que al no haber usado el "tramo" en las estaciones de medida, me salen muchas observaciones realizadas por la misma estación que se encuentra situada en diferentes tramos.
He pensado en añadir el tramo a las estaciones de medida pero la única forma que se me ocurre para incluirlo en la URI sería mediante un hash (algo que no me parece demasiado descriptivo) ya que si añadiese directamente el tramo a la URI, esta quedaría demasiado grande.
Alguna idea?

**Comment by ocorcho** [comment]
¿Puedes poner ejemplos en este tipo de issues? Si no, es muy difícil entender a qué te refieres.

**Comment by juanbm99** [comment]
Sí, digamos que hay varios sensores que se encuentran en la calle Ronda de Boltana en diferentes tramos:
- Calle: Ronda Boltana 
- Tramo: Carretera De Huesca-Calle La Fragua
- Num_Instal: 574

- Calle: Ronda Boltana
- Tramo: Luciano Gracia-Avenida Las Majas De Goya
- Num_Instal: 575

Actualmente yo tengo puesto simplemente que ese sensor se agrupa en uno con URI: `http://datos.linkeddata.es/zaragoza/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/ronda-de-boltana`

Pero claro estos dos sensores tienen diferentes valores para sus observaciones por lo que sería lógico realmente crear una URI para cada uno de ellos:

- La idea que comentaba era hacer un hash del tramo y añadirlo a la URI pero no me parece muy representativo:
`http://datos.linkeddata.es/zaragoza/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/ronda-de-boltana-e1a7406957804f1727601fd097a1b40e`

- Otra forma tal vez sea incluir el num_instal en la URI:
`http://datos.linkeddata.es/zaragoza/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/ronda-de-boltana-574`
- Si ves que no hay problema en que varias observaciones de un mismo periodo tengan la misma estación como referencia lo dejo así y obvio el tramo

**Comment by ocorcho** [comment]
Si el num_install es único y tiene pinta de ser la clave primaria en la fuente de datos (es el identificador de la estación) eso es lo que tiene que ir en la URI, y no la calle.
`
http://datos.linkeddata.es/zaragoza/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/574
`

**Comment by juanbm99** [comment]
Okey perfecto, he pensado en poner el tramo referido a la estación de medida con: 
`<http://datos.linkeddata.es/zaragoza/recurso/medio-ambiente/contaminacion-acustica/estacion-medida/571> <http://www.w3.org/2002/07/owl#intersectionOf> "Carretera De Huesca-Calle La Fragua"^^<http://www.w3.org/2001/XMLSchema#string>`

No se si es correcto ya que esta propiedad no aparecer referida en la ontología de Contaminacion Acustica.
¿Que te parece?

**Comment by ocorcho** [comment]
No, no... Esa propiedad no tiene nada que ver con un tramo. 
Si no recuerdo mal, deberías usar la propiedad tramoVia de la ontología de callejero.

**Comment by juanbm99** [comment]
Listo, datos generados
