### ISSUE TITLE
Problema Mapeado RuidoDiario2020.csv

### ISSUE THREAD

**Issue by juanbm99** [juanbm99/TFG-OpenCityData-JuanBernal#6]
Estoy realizando el RML para mapear el ruido diario del año 2020 a través de la ontología y tengo que hacer uso de la entidad "Observación" como sujeto de las tripletas, el problema me surge que no sé como identificar cada observación (es decir, no sé que URI debe llevar cada observación) ya que hay varias observaciones en la misma fecha, realizadas desde la misma estación.

Se os ocurre como poder identificar las observaciones?

**Comment by ocorcho** [comment]
Already covered in #8 ?
