### ISSUE TITLE
Object Properties: tipo_medicion y tipo_de_intervalo_referencia

### ISSUE THREAD

**Issue by juanbm99** [juanbm99/TFG-OpenCityData-JuanBernal#7]
Leyendo la documentación de la ontología he visto que estas dos object properties hacen referencia a las diferentes tipos de mediciones (LAeq, LAs01...) y a los intervalos en los que se hace la medicion (T:Total, D:Diurno, E: Vespertino, N:Nocturno) respectivamente. Estos datos se encuentran en el CSV sin embargo no sé como relacionarlos al tratarse de una object propertie y no de una data propertie de Observación. 

Estas object properties tienen como dominio "Observación" y como range la entidad "Concept" (entidad genérica que hace referencia a un concepto en general). Podría llegar a establecer en el RML una relación entre estas dos entidades para posteriormente poner a cada "concepto" una data propertie como la de "has simple result" sin embargo vuelvo a tener entonces el mismo problema que con las Observaciones y es que no sé que URI poner para identificar un "Concept".

Alguna idea?

**Comment by ocorcho** [comment]
Si no me equivoco, la relación (al ser una object property) se hace a un skos:Concept, dado que el conjunto de valores está predefinido (es decir, es lo que sería un valor enumerado). Por tanto, en RML habría que generar la URI del skos:Concept correspondiente.

@paoespinozarias confirma este punto

**Comment by juanbm99** [comment]
Si por cada entrada del CSV tengo 6 valores de medidas (LAeq, LAs01, LAs10, LAs50, LAs90, LAs99), tendría que hacer una URI para cada uno de estos valores? 

O tendría que generar una URI para skos:Concept (no sé que info debería contener esta URI) y posteriormente añadir los valores anteriormente mencionados con una data propertie?

**Comment by juanbm99** [comment]
Hola @ocorcho , estoy a falta de cómo afrontar el problema de las URIs de skos:Concept para acabar la generación de datos de Contaminación acústica y presentar una primera versión, alguna sugerencia acerca de como plantear las URIs de skos:Concept? Luego una vez obtenida esa URI, te parece correcto relacionar los valores de las mediciones a través de la data propertie de "has simple result"?

**Comment by ocorcho** [comment]
¿Puedes comprobar si se corresponden con algunos de los SKOS que se han generado ya? Todos ellos están disponibles en el repositorio https://github.com/opencitydata/listas-codigos-skos

- http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-emisor-predominante
- http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-intervalo-referencia
- http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica

**Comment by juanbm99** [comment]
Efectivamente coinciden con esos SKOS. Por ejemplo, centrándonos en la object property definida en la ontología como "tipo de medición" (http://vocab.ciudadesabiertas.es/def/medio-ambiente/contaminacion-acustica#tipoMedida) , para relacionar esta object property entre una Observación (URI con hash) y una URI del tipo SKOS (http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica)
para que la URI del SKOS fuese distinguible del resto sería buena idea incluir en la URI el valor de la medición?
p.e: <http://vocab.linkeddata.es/datosabiertos/kos/medio-ambiente/contaminacion-acustica/tipo-medicion-contaminacion-acustica/LAS10/70.2> (aunque pensandolo bien puede que haya valores que coincidan así que lo mejor sería igual generar un hash entre el valor + fecha

**Comment by ocorcho** [comment]
No, el URI del SKOS con cambia. El tipo de medición es siempre el mismo. Genera un ejemplo de dos observaciones, y verás cómo no tienes que cambiar estos valores.
