### ISSUE TITLE
Mapping RML no termina debido a la cantidad de Datos

### ISSUE THREAD

**Issue by juanbm99** [juanbm99/TFG-OpenCityData-JuanBernal#9]
Al ejecutar el mapping RML sobre el csv de ruidoDiario2020 (~46000 filas) y sobre el csv de ruidoDiario2021(~6500 filas) el mapping no termina de ejcutarse (he llegado a esperar unos 20 min) cuando generalmente esto tarda unos pocos segundos. He pensado en fragmentar el CSV en varios y aplicar el mapping sobre estos fragmentos, 

que os parece?

**Comment by ocorcho** [comment]
No están disponibles en GitHub los RML, así que no puedo analizarlo. Indica con links a los ficheros qué CSVs son y qué ficheros RML son, de tal manera que @ArenasGuerreroJulian pueda revisar este proceso de transformación y @dachafra pueda analizar si es un buen ejemplo para mostrar las ventajas de Morph-KGC

**Comment by arenas-guerrero-julian** [comment]
@juanbm99 Además de como dice Oscar de que des acceso a los mappings, ¿qué herramienta estás usando para generar el RDF?. Fragmentar los CSVs no me parece buena idea si los mappings tienen _joins_, en todo caso fragmentaría los mappings o los normalizaría (hacer que cada triples map tengan un solo predicate object map).

**Comment by juanbm99** [comment]
RML RuidoDiario 2020 (faltan propiedades aún): https://github.com/juanbm99/TFG-OpenCityData-JuanBernal/blob/main/data/mappings/ruido2020-RML.rml

CSV RuidoDiario2020: https://github.com/juanbm99/TFG-OpenCityData-JuanBernal/blob/main/data/preprocessed/RuidoDiario2020/RuidoDiario2020_v2.csv

**Comment by juanbm99** [comment]
Para generar el rdf estoy utilizando el rmlmapper.jar

**Comment by arenas-guerrero-julian** [comment]
rmlmapper es **extremadamente** lento, probablemente es la herramienta. Soluciones que yo probaría por orden:

1. rmlmapper creo que tiene una opción para que no elimine duplicados. Si no te es importante que genere tripletas duplicadas, prueba a correr rmlmapper con esta opción (el bottleneck del engine está en el algoritmo para eliminar duplicados). 
2. Si necesitas eliminar duplicados, o si rmlmapper sigue siendo demasiado lento puedes probar con SDM-RDFizer (https://github.com/SDM-TIB/SDM-RDFizer), es python. Para CSV sabemos que tiene un bottleneck ahora mismo que tienen que solucionar, pero con tus datos creo debería terminar sin problemas.
3. Si aun así sigue sin terminar puedes probar con R2RML-F (https://github.com/chrdebru/r2rml) (es un jar también), que es la que mejor funciona para CSV ahora mismo. Acepta los mappings en R2RML, convertir de RML a R2RML es un momento. Si eliges esta herramienta escríbeme y te explico para que vayas a tiro hecho.

**Comment by juanbm99** [comment]
1. He probado a dejar duplicados y nada sigue sin funcionar.
2. Probado con SDM-RDFizer pero se queda pillado también:
![image](https://user-images.githubusercontent.com/43373725/111066224-238c9300-84be-11eb-8b84-5c1586694f7b.png)
3. Solo me queda por probar la herramienta que mencionas así que si quieres te dejo mi correo para comunicarnos por ahí:
Correo: juanbernalmencia@gmail.com

**Comment by dachafra** [comment]
@juanbm99 veo que en el mapping hay un self-join, podrías probar a eliminar la condición ([esta linea](https://github.com/juanbm99/TFG-OpenCityData-JuanBernal/blob/main/data/mappings/ruido2020-RML.rml#L37) y el child/parent) y sólo dejar el parentTriplesMap? El resultado en el SDM-RDFizer debería ser el mismo que con la condición. Quizá así mejores el performance....

**Comment by juanbm99** [comment]
He probado con SDM-RDFizer y termina (aunque es cierto que para el dataset de RuidoDiario2020 (47k filas) tarda unos 20 min. Voy a probar ahora con lo que me has dicho @dachafra

**Comment by juanbm99** [comment]
Eliminando esa línea el mapping es inmediato pero es verdad que no me lo hace correctamente ya que donde debería poner la URI de la estación de medida simplemente pone el nombre la columna del CSV.
![image](https://user-images.githubusercontent.com/43373725/111067071-a4e62480-84c2-11eb-9982-88beed223ac1.png)
@dachafra alguna idea de por qué puede ser esto?

**Comment by dachafra** [comment]
Curioso, me da que es un error del engine, hay que abrir un issue (en inglés) aquí con ese error: https://github.com/SDM-TIB/SDM-RDFizer/issues sube los datos y los mappings, además de que te está metiendo la URI base en la generación de los subjects...

He probado a en vez de poner rml:reference a poner rr:template "{URI_ESTACION}" y así lo hace bien, aunque sigue metiendo la uri base de por medio, ábrele un issue, yo lo gestiono.

Por cierto, cuidado con abrir los CSVs con notepad o similares, te ha metido BOM Chars que debes limpiar: https://stackoverflow.com/questions/45240387/how-can-i-remove-the-bom-from-a-utf-8-file

**Comment by juanbm99** [comment]
Issue abierta, en qué CSV dices que me ha metido BOM Chars? La codificación del CSV me dice que está en UTF-8 sin BOM  y no encuentro ninguno por ninguna parte
